### ISSUE TITLE
Hi @Milazzo11 - SC-score here

### ISSUE THREAD

**Issue by paulsblackfriday** [Milazzo11/Snapscore-Bot#2]
HI can you we get this updated somehow? 
https://github.com/Milazzo11/Snapscore-Bot/commit/562958bdb9ea4577d841eb93fd00dd81511e040f

**Comment by Milazzo11** [comment]
> 

Hey.  So as of now, it appears that the builders of the snapchat web app didn’t do a very good job with memory management… I can try and find a workaround, but I’m not sure what that would be.

Obviously having a “reboot” option would fix the issue; but unfortunately it would also require the user to manually log back in… so there isn’t much point.  As of now, you’re probably best to run it for a few hours at a time, then manually restart it.  Hopefully I can find a workaround soon, though.

**Comment by paulsblackfriday** [comment]
So wait I know bot.py just run it in a cmd windows panel? Or does it open a chrome driver ?  Or does it ask me to log in to my Snapchat ; so it’ll likely kick me out of my Snapchat in my mobile iOS phone ? Then just log back in to it in my phone after using it in a windows machines cmd terminal? 

Paul

**Comment by Milazzo11** [comment]
First, go into the boy.py file and add your email and password into the variables at the top of the code.  Then, run bot.py and follow the on-screen directions.

It should then ask you to verify the login kn your phone; do that, theb navigate to the chat page with the account you want to execute the bot for.  Then click enter and run it — it should send continuous snaps for a couple hours before the memory leak issues happen.

**Comment by paulsblackfriday** [comment]
Should i do this with dummy profiles i dont know or with actual friend i
know?  I had some random person once say to me, SPAM! .lol But it was a
random person i dont know.
And will it snap what i want to send or does it snap send a random clip ?

**Comment by paulsblackfriday** [comment]
error i got i think i need chromedriver 103...x

C:\Users\PAULMUSICDAW\Downloads\Github Apps\Snapscore-Bot>python bot.py
Traceback (most recent call last):
  File "C:\Users\PAULMUSICDAW\Downloads\Github Apps\Snapscore-Bot\bot.py",
line 287, in <module>
    main()
  File "C:\Users\PAULMUSICDAW\Downloads\Github Apps\Snapscore-Bot\bot.py",
line 273, in main
    driver = init()
  File "C:\Users\PAULMUSICDAW\Downloads\Github Apps\Snapscore-Bot\bot.py",
line 83, in init
    driver = uc.Chrome(use_subprocess=True)
  File
"C:\Users\PAULMUSICDAW\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\undetected_chromedriver\__init__.py",
line 429, in __init__
    super(Chrome, self).__init__(
  File
"C:\Users\PAULMUSICDAW\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chrome\webdriver.py",
line 81, in __init__
    super().__init__(
  File
"C:\Users\PAULMUSICDAW\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chromium\webdriver.py",
line 106, in __init__
    super().__init__(
  File
"C:\Users\PAULMUSICDAW\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py",
line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File
"C:\Users\PAULMUSICDAW\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\undetected_chromedriver\__init__.py",
line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver,
self).start_session(
  File
"C:\Users\PAULMUSICDAW\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py",
line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File
"C:\Users\PAULMUSICDAW\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py",
line 444, in execute
    self.error_handler.check_response(response)
  File
"C:\Users\PAULMUSICDAW\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py",
line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error:
cannot connect to chrome at 127.0.0.1:60251
from session not created: This version of ChromeDriver only supports Chrome
version 108
Current browser version is 103.0.5060.66
Stacktrace:
Backtrace:
        (No symbol) [0x00B5F243]
        (No symbol) [0x00AE7FD1]
        (No symbol) [0x009DD04D]
        (No symbol) [0x009FF6B4]
        (No symbol) [0x009F8424]
        (No symbol) [0x009F8201]
        (No symbol) [0x00A2F056]
        (No symbol) [0x00A2EB2A]
        (No symbol) [0x00A28386]
        (No symbol) [0x00A0163C]
        (No symbol) [0x00A0269D]
        GetHandleVerifier [0x00DF9A22+2655074]
        GetHandleVerifier [0x00DECA24+2601828]
        GetHandleVerifier [0x00C08C0A+619850]
        GetHandleVerifier [0x00C07830+614768]
        (No symbol) [0x00AF05FC]
        (No symbol) [0x00AF5968]
        (No symbol) [0x00AF5A55]
        (No symbol) [0x00B0051B]
        BaseThreadInitThunk [0x76E400F9+25]
        RtlGetAppContainerNamedObjectPath [0x77797BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77797B8E+238]

**Comment by paulsblackfriday** [comment]
How can i make this pull or import chromedriver 103.   i currently have
chrome 108 installed normal on a windows 10 machine code looks or wants
something else?

bot.py has this currently :

import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from time import time, sleep
from random import random
# manages imports

**Comment by paulsblackfriday** [comment]
Oh I attached a short clip video if I can view it, it shows that it’s trying with the current version of Snapchat to click hot spots recorded but the first setup round was more Ricky because I had to choose icons and side icons too where they are actually located now in the new Snapchat today on IOS PHONE. Can u set it up to ask correctly ?
